name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pardivkamishetty
          base: header, activity, community, repositories
          config_output: svg
          filename: github-metrics.svg
